name: Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Use Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app

    - name: List available simulators
      run: xcrun simctl list devices

    - name: Test Sample
      run: ./Scripts/test_sample
